#!/bin/bash
TARGET=$1
if [[ -z "$TARGET" ]]; then
    TARGET="$(hostname)"
fi
echo $TARGET
case "$TARGET" in
    "ksanti")
COMMAND="cp *.uf2 /Volumes/Users/seth/Desktop/share/qmk-firmware"
        ;;
    "pc")
COMMAND="cp *.uf2 /mnt/c/Users/seth/Desktop/share/qmk-firmware/"
        ;;
    "191-grosvenor-imac.local")
COMMAND="scp *.uf2 191-grosvenor-imac.local:~/Desktop/"
        ;;
    "lapdesk.local")
DESTINATION="/Volumes/RPI-RP2"
COMMAND="cp hazel_bad_wings_SethMilliken.uf2 ${DESTINATION}"
printf "Waiting for ${DESTINATION}"
until [ -d "${DESTINATION}" ]; do
    printf "."
    sleep 1
done
printf "\n"
        ;;
esac
echo "$COMMAND"
$COMMAND
